// Generated by CoffeeScript 1.3.1

/* Licensed under the Apache License, Version 2.0. See footer for details
*/


(function() {
  var specHelpers;

  specHelpers = new (require("./spec-helpers"));

  describe("console.table(scalar)", function() {
    beforeEach(function() {
      return specHelpers.beforeEach(this);
    });
    afterEach(function() {
      return specHelpers.afterEach(this);
    });
    it("should handle console.table(null)", function() {
      console.table(null);
      return expect(specHelpers.lines).toEqualLines("| value |\n---------\n| null  |");
    });
    it("should handle console.table(undefined)", function() {
      console.table(void 0);
      return expect(specHelpers.lines).toEqualLines("| value |\n---------\n|       |");
    });
    it("should handle console.table('x')", function() {
      console.table('x');
      return expect(specHelpers.lines).toEqualLines("| value |\n---------\n| x     |");
    });
    it("should handle console.table(1)", function() {
      console.table(1);
      return expect(specHelpers.lines).toEqualLines("| value |\n---------\n|     1 |");
    });
    it("should handle console.table(false)", function() {
      console.table(false);
      return expect(specHelpers.lines).toEqualLines("| value |\n---------\n| false |");
    });
    it("should handle console.table(function)", function() {
      console.table(function() {});
      return expect(specHelpers.lines).toEqualLines("||");
    });
    it("should handle console.table(NaN)", function() {
      console.table(1 / 'x');
      return expect(specHelpers.lines).toEqualLines("| value |\n---------\n| NaN   |");
    });
    return xit("should ...", function() {
      var line, _i, _len, _ref, _results;
      console.table(function() {});
      expect(specHelpers.lines).toEqualLines("||");
      _ref = specHelpers.lines;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i];
        _results.push(console.log(line));
      }
      return _results;
    });
  });

  /*        
  #-------------------------------------------------------------------------------
  # Copyright 2012 Patrick Mueller
  # 
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  # 
  #    http://www.apache.org/licenses/LICENSE-2.0
  # 
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  #-------------------------------------------------------------------------------
  */


}).call(this);
