// Generated by CoffeeScript 1.3.1

/* Licensed under the Apache License, Version 2.0. See footer for details
*/


(function() {
  var SpecHelpers, toEqualLines, trimBlanks;

  SpecHelpers = (function() {

    SpecHelpers.name = 'SpecHelpers';

    function SpecHelpers() {
      this.lines = [];
    }

    SpecHelpers.prototype.beforeEach = function(suite) {
      var _this = this;
      this.lines = [];
      console.table = require("../lib/console-table");
      console.table.logger = function(line) {
        return _this.consoleLog(line);
      };
      return suite.addMatchers({
        toEqualLines: toEqualLines
      });
    };

    SpecHelpers.prototype.afterEach = function(suite) {
      console.table.logger = null;
      return this.lines = null;
    };

    SpecHelpers.prototype.consoleLog = function(line) {
      return this.lines.push(line);
    };

    return SpecHelpers;

  })();

  trimBlanks = function(string) {
    return string.replace(/^\s+|\s+$/g, "");
  };

  toEqualLines = function(expected) {
    var aItem, eItem, failMessage, i, _i, _ref;
    failMessage = function() {
      return "Expected table was actually\n" + (this.actual.join('\n'));
    };
    if (typeof expected === "string") {
      expected = trimBlanks(expected);
      expected = expected.split("\n");
    }
    if (this.actual.length !== expected.length) {
      this.message = failMessage;
      return false;
    }
    for (i = _i = 0, _ref = this.actual.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      aItem = this.actual[i];
      eItem = expected[i];
      if (aItem !== eItem) {
        this.message = failMessage;
        return false;
      }
    }
    return true;
  };

  if (typeof require === "undefined") {
    window.SpecHelpers = SpecHelpers;
  } else {
    module.exports = SpecHelpers;
  }

  /*
  #-------------------------------------------------------------------------------
  # Copyright 2012 Patrick Mueller
  # 
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  # 
  #    http://www.apache.org/licenses/LICENSE-2.0
  # 
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  #-------------------------------------------------------------------------------
  */


}).call(this);
